### PR TITLE
Add client for making RPCs to coordinator.

### PR DESCRIPTION
**Pull request by benjmarks22**

### CODE REVIEW

**Comment by benjmarks22** [comment]
I still need to add flags to the client so that it can send different RPCs based on the command line (e.g. to different ports). I also need to create an end to end script that brings up the relevant cohorts and coordinator with the right ports and sends requests from the client.

**Comment by benjmarks22** [comment]
Also, @heronyang it doesn't work yet with the blockchain since that's not yet connected with the C++ blockchain interface. Are you planning on handling that or should I?

**Comment by heronyang** [comment]
I plan to implement the contract adapter client (aka `src/blockchain/two_phase_commit.cc`) tomorrow. Let me know if I'm blocking the end-to-end integration and feel free to take it over if it's faster.

**Comment by benjmarks22** [comment]
Merging so I can test end to end with the blockchain adapter.

**Pull request merged**
